## This YAML File contains the needed variables in order to conigure and upload your portfolio
#  files to the cloud.

Project:
  Name: "*PROJECTNAME*"
  RootDirectory: "../"
  SourceDirectory: "*SRC/"
  IgnoreFiles: ["*FILES_TO_IGNORE"]
  FirebaseCredentials: "/*FIREBASE_CREDENTIALs_JSON*"
  CredentialsPath: "/../*CREDENTIALS_DIRECTORY*"
  BucketPath: "*FIREBASE_STORAGE_BUCKET_NAME*"
  Extensions: ["*FILES_YOU_WANT_TO_DEEP_COPY",.js", ".jsx", ".ts", ".css", ".scss"]

